language: go

go:
  - 1.10.x

env:

before_install:
 #- go get -u github.com/haya14busa/goverage
  - go get -u github.com/tesujiro/goa

script:
  - go test -v -coverprofile=coverage.txt -covermode=count . ./vm

after_success:
  - bash <(curl -s https://codecov.io/bash)
