language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x

env:

before_install:
 #- go get -u github.com/haya14busa/goverage
  - go get -u github.com/tesujiro/ago

script:
  - go test -v -coverprofile=coverage.txt -covermode=count . ./vm

after_success:
  - bash <(curl -s https://codecov.io/bash)
